### ISSUE TITLE
Кнопка не активируется

### ISSUE THREAD

**Issue by Netlenskiy** [Gizmodo/MMTR_Task#10]
https://user-images.githubusercontent.com/11318926/151130102-9c51092e-5460-4b21-84e0-16ddae913961.mp4

**Comment by Gizmodo** [comment]
Удалось воспроизвести ошибку: возникает именно при сворачивании приложения с переходом на стороннее (копирование ключа) и последующим возвратом к PetSide. Проблема в неработающем слушателе.

**Comment by Gizmodo** [comment]
Проблема устранена
