### ISSUE TITLE
Этот код не работает)

### ISSUE THREAD

**Issue by Netlenskiy** [Gizmodo/MMTR_Task#32]
https://github.com/Gizmodo/MMTR_Task/blob/f045203ed63277871f7d6b56262bdffd4e553d3b/app/src/main/java/com/example/fragmentvm/App.kt#L36

![image](https://user-images.githubusercontent.com/11318926/167873891-0417568c-7937-4371-a840-21947632c534.png)

**Comment by Gizmodo** [comment]
Fix #32
